const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
function show(id){['auth','app','admin'].forEach(x=>$('#'+x).classList.add('hidden'));if(id)$('#'+id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{show('auth');const v=b.dataset.view;$('#registerForm').classList.toggle('hidden',v!=='register');$('#loginForm').classList.toggle('hidden',v!=='login');$('#authTitle').textContent=v==='register'?'Create account':'Sign in'}));
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast(d.message);loadMe()}catch(e){toast(e.message)}});
$('#registerForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/register',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast(d.message);e.target.reset();loadMe()}catch(e){toast(e.message)}});
$('#depositForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/deposit',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast(d.message);e.target.reset();if(d.checkoutUrl)window.location.href=d.checkoutUrl;else loadDashboard()}catch(e){toast(e.message)}});
$('#withdrawForm').addEventListener('submit',async e=>{e.preventDefault();try{toast((await api('/api/withdraw',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).message);e.target.reset();loadDashboard()}catch(e){toast(e.message)}});

$('#setup2fa').addEventListener('click',async()=>{try{const d=await api('/api/2fa/setup',{method:'POST'});$('#twofaBox').innerHTML=`Secret: <code>${d.secret}</code><br>Enter this secret in an authenticator app, then enter the 6-digit code below.`;$('#enable2faForm').classList.remove('hidden')}catch(e){toast(e.message)}});
$('#enable2faForm').addEventListener('submit',async e=>{e.preventDefault();try{toast((await api('/api/2fa/enable',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))})).message);e.target.reset();loadDashboard()}catch(e){toast(e.message)}});
$('#logoutBtn').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});$('#adminLogout').addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});location.reload()});
async function loadMe(){try{const d=await api('/api/me');if(!d.authenticated){show(null);return}if(d.user.role==='admin'){show('admin');loadAdmin()}else{show('app');loadDashboard()}}catch(e){toast(e.message)}}
async function loadDashboard(){const d=await api('/api/dashboard');$('#welcome').textContent='Welcome, '+d.user.full_name;$('#balance').textContent='₦'+Number(d.user.balance).toLocaleString(undefined,{minimumFractionDigits:2});$('#refCount').textContent=d.referrals.count;$('#refCode').textContent=d.user.referral_code;const r=await api('/api/referrals');$('#refLink').textContent=r.link;$('#txBody').innerHTML=d.transactions.length?d.transactions.map(x=>`<tr><td>${x.type}</td><td>₦${Number(x.amount).toLocaleString(undefined,{minimumFractionDigits:2})}</td><td>${x.provider||'—'}</td><td class="status ${x.status}">${x.status}</td><td>${new Date(x.created_at+'Z').toLocaleString()}</td></tr>`).join(''):'<tr><td colspan="5">No transactions yet.</td></tr>'}
async function loadAdmin(){const s=await api('/api/admin/summary');$('#adminUsers').textContent=s.users;$('#adminDeposits').textContent='₦'+Number(s.deposits).toLocaleString();$('#adminWithdrawals').textContent='₦'+Number(s.withdrawals).toLocaleString();$('#adminPending').textContent=s.pending;const tx=await api('/api/admin/transactions');$('#adminTxBody').innerHTML=tx.map(x=>`<tr><td>${x.full_name}<br><small>${x.email}</small></td><td>${x.type}</td><td>₦${Number(x.amount).toLocaleString()}</td><td class="status ${x.status}">${x.status}</td><td>${x.status==='pending'?`<button onclick="txAction(${x.id},'approve')">Approve</button> <button class="outline" onclick="txAction(${x.id},'reject')">Reject</button>`:'—'}</td></tr>`).join('');const us=await api('/api/admin/users');$('#usersBody').innerHTML=us.map(x=>`<tr><td>${x.full_name}</td><td>${x.email}</td><td>₦${Number(x.balance).toLocaleString()}</td><td>${x.twofa_enabled?'On':'Off'}</td><td>${x.role}</td></tr>`).join('')}
async function txAction(id,action){try{toast((await api('/api/admin/transactions/'+id+'/'+action,{method:'POST'})).message);loadAdmin()}catch(e){toast(e.message)}}window.txAction=txAction;loadMe();
